version: "3"
services:
  joinpage:
    image: danjellz/http-server:latest
    ports:
      # DASH in numbers
      - "3274:8080"
    volumes:
      - ./frontend:/public
    networks:
       - emission

networks:
  emission:

volumes:
  mongo-data:

