version: "3"
services:
  joinpage:
    build:
        context: frontend
        dockerfile: docker/Dockerfile
    ports:
      # DASH in numbers
      - "3274:8080"
    networks:
       - emission

networks:
  emission:
