version: "3"
services:
  joinpage:
    image: shankari/op-join-page:dev-latest
    build:
        context: .
        dockerfile: frontend/Dockerfile.dev
    ports:
      # DASH in numbers
      - "3274:5050"
    volumes:
      - ./frontend:/public
    networks:
       - emission

networks:
  emission:
